"""City preset configurations for Baumkataster WFS/REST services."""

PRESETS = {
    "Hamburg (Straßenbäume)": {
        "service_type": "wfs",
        "wfs_url": "https://geodienste.hamburg.de/HH_WFS_Strassenbaumkataster",
        "type_name": "de.hh.up:strassenbaumkataster",
        "wfs_version": "2.0.0",
        "output_format": "application/geo+json",
        "typename_param": "typeName",
        "native_crs": "EPSG:25832",
        "center": [53.55, 10.0],
        "field_map": {
            "baumnummer": "baum_id",
            "art_deutsch": "art_deutsch",
            "gattung_deutsch": "gattung_deutsch",
            "art_latein": "art_latein",
            "gattung_latein": "gattung_latein",
            "stammumfang": "stammumfang",
            "kronendurchmesser": "kronendurchmesser",
            "baumhoehe": "baumhoehe",
            "pflanzjahr": "pflanzjahr",
            "strasse": "strasse",
            "hausnummer": "hausnummer",
            "bezirk": "bezirk",
        },
    },
    "Hamburg (3D Sommerbäume + Höhe)": {
        "service_type": "3dtiles",
        "tileset_url": "https://daten-hamburg.de/gdi3d/datasource-data/Strassenbaumkataster_Sommerbaeume/tileset.json",
        "native_crs": "EPSG:4326",
        "center": [53.55, 10.0],
        "field_map": {
            "Baumnummer": "baum_id",
            "Baumart": "art_deutsch",
            "Gattung": "gattung_deutsch",
            "Stammumfang": "stammumfang",
            "Kronendurchmesser": "kronendurchmesser",
            "Hoehe_aus_ALS": "baumhoehe",
            "Pflanzjahr": "pflanzjahr",
            "Straße": "strasse",
            "Hausnummer": "hausnummer",
            "Bezirk": "bezirk",
        },
    },
    "Hamburg (HPA / Hafenbäume)": {
        "service_type": "wfs",
        "wfs_url": "https://geodienste.hamburg.de/HH_WFS_Strassenbaumkataster",
        "type_name": "de.hh.up:strassenbaumkataster_hpa",
        "wfs_version": "2.0.0",
        "output_format": "application/geo+json",
        "typename_param": "typeName",
        "native_crs": "EPSG:25832",
        "center": [53.53, 9.97],
        "field_map": {
            "baumid": "baum_id",
            "sorte": "art_deutsch",
            "stammumfang": "stammumfang",
            "kronendurchmesser": "kronendurchmesser",
            "pflanzjahr": "pflanzjahr",
            "strasse": "strasse",
            "hausnummer": "hausnummer",
        },
    },
    "Berlin (Straßenbäume)": {
        "service_type": "wfs",
        "wfs_url": "https://gdi.berlin.de/services/wfs/baumbestand_an_strassen",
        "type_name": "baumbestand_an_strassen:baumbestand_an_strassen",
        "wfs_version": "2.0.0",
        "output_format": "application/json",
        "typename_param": "typeNames",
        "native_crs": "EPSG:25833",
        "center": [52.52, 13.405],
        "field_map": {
            "baumid": "baum_id",
            "art_dtsch": "art_deutsch",
            "gattung_deutsch": "gattung_deutsch",
            "art_bot": "art_latein",
            "gattung": "gattung_latein",
            "stammumfg": "stammumfang",
            "kronedurch": "kronendurchmesser",
            "baumhoehe": "baumhoehe",
            "pflanzjahr": "pflanzjahr",
            "strname": "strasse",
            "hausnr": "hausnummer",
            "bezirk": "bezirk",
        },
    },
    "Berlin (Anlagenbäume)": {
        "service_type": "wfs",
        "wfs_url": "https://gdi.berlin.de/services/wfs/baumbestand_in_anlagen",
        "type_name": "baumbestand_in_anlagen:baumbestand_in_anlagen",
        "wfs_version": "2.0.0",
        "output_format": "application/json",
        "typename_param": "typeNames",
        "native_crs": "EPSG:25833",
        "center": [52.52, 13.405],
        "field_map": {
            "baumid": "baum_id",
            "art_dtsch": "art_deutsch",
            "gattung_deutsch": "gattung_deutsch",
            "art_bot": "art_latein",
            "gattung": "gattung_latein",
            "stammumfg": "stammumfang",
            "kronedurch": "kronendurchmesser",
            "baumhoehe": "baumhoehe",
            "pflanzjahr": "pflanzjahr",
            "strname": "strasse",
            "hausnr": "hausnummer",
            "bezirk": "bezirk",
        },
    },
    "Köln": {
        "service_type": "wfs",
        "wfs_url": "https://geoportal.stadt-koeln.de/arcgis/services/Baumkataster/MapServer/WFSServer",
        "type_name": "Baumkataster:Baumkataster",
        "wfs_version": "2.0.0",
        "output_format": "application/json; subtype=geojson",
        "typename_param": "typeNames",
        "native_crs": "EPSG:4326",
        "center": [50.9375, 6.9603],
        "field_map": {
            "OBJECTID": "baum_id",
            "Baumart_de": "art_deutsch",
            "Gattung_de": "gattung_deutsch",
            "Baumart_la": "art_latein",
            "Gattung_la": "gattung_latein",
            "Stammumfan": "stammumfang",
            "Kronendurchmesser": "kronendurchmesser",
            "Hoehe": "baumhoehe",
            "Pflanzjahr": "pflanzjahr",
            "Strasse": "strasse",
            "Hausnummer": "hausnummer",
            "Stadtteil": "bezirk",
        },
    },
    "Leipzig": {
        "service_type": "wfs",
        "wfs_url": "https://geodienste.leipzig.de/arcgis/services/Baumkataster/MapServer/WFSServer",
        "type_name": "Baumkataster:Baumstandorte",
        "wfs_version": "2.0.0",
        "output_format": "application/json",
        "typename_param": "typeName",
        "native_crs": "EPSG:25833",
        "center": [51.3397, 12.3731],
        "field_map": {
            "OBJECTID": "baum_id",
            "Baumart": "art_deutsch",
            "Gattung": "gattung_deutsch",
            "Baumart_la": "art_latein",
            "Gattung_la": "gattung_latein",
            "Stammumfan": "stammumfang",
            "Kronenbrei": "kronendurchmesser",
            "Baumhoehe": "baumhoehe",
            "Pflanzjahr": "pflanzjahr",
            "Strasse": "strasse",
            "Hausnummer": "hausnummer",
            "Stadtteil": "bezirk",
        },
    },
    "Frankfurt am Main": {
        "service_type": "arcgis_rest",
        "rest_url": "https://geoinfo.frankfurt.de/server/rest/services/Baumkataster/Baumkataster/MapServer/0",
        "native_crs": "EPSG:4326",
        "center": [50.1109, 8.6821],
        "field_map": {
            "OBJECTID": "baum_id",
            "BAUMART_DEUTSCH": "art_deutsch",
            "GATTUNG_DEUTSCH": "gattung_deutsch",
            "BAUMART_LATEIN": "art_latein",
            "GATTUNG_LATEIN": "gattung_latein",
            "STAMMUMFANG": "stammumfang",
            "KRONENDURCHMESSER": "kronendurchmesser",
            "BAUMHOEHE": "baumhoehe",
            "PFLANZJAHR": "pflanzjahr",
            "STRASSE": "strasse",
            "HAUSNUMMER": "hausnummer",
            "STADTTEIL": "bezirk",
        },
    },
    "Rostock": {
        "service_type": "wfs",
        "wfs_url": "https://geo.sv.rostock.de/geodienste/strassenbaumkataster/wfs",
        "type_name": "strassenbaumkataster:HRO_Strassenbaumkataster_Strassenbaeume",
        "wfs_version": "2.0.0",
        "output_format": "application/json",
        "typename_param": "typeName",
        "native_crs": "EPSG:25833",
        "center": [54.0887, 12.1407],
        "field_map": {
            "uuid": "baum_id",
            "art_deutsch": "art_deutsch",
            "gattung_deutsch": "gattung_deutsch",
            "art_latein": "art_latein",
            "gattung_latein": "gattung_latein",
            "stammumfang": "stammumfang",
            "kronendurchmesser": "kronendurchmesser",
            "baumhoehe": "baumhoehe",
            "pflanzjahr": "pflanzjahr",
            "strasse_name": "strasse",
            "hausnummer": "hausnummer",
            "gemeindeteil_name": "bezirk",
        },
    },
}
